/* This file holds the finished postfix expression generated by the parser. 
 * Author: Joshua Wilkes
 * Version: 1.0
 * Last Updated: 02/28/2019
*/

#include "registerStack.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct registerNode
{
  char word[20];
  registerNode *next;
  registerNode *last;
};

registerNode *registerHead = NULL;
registerNode *registerPointer = NULL;

/* Method to initially create the token linked list */
registerNode *createRegisterStack(char newWord[])
{
  registerHead = (registerNode *)malloc(sizeof(registerNode));
  strcpy(registerHead->word, newWord);
  registerHead->next = NULL;
  registerHead->last = NULL;
  registerPointer = registerHead;
  return registerHead;
}

/* Method to push new data into token linked list */
void pushToRegister(char newWord[])
{
  printf("pushToRegister started, registerPointer: %s\n", registerPointer->word);
  if (registerPointer == NULL)
  {
    printf("registerPointer was null\n");
    createRegisterStack(newWord);
  }
  else
  {
    printf("else 1");
    // registerNode *newNode = (registerNode *)malloc(sizeof(registerNode));
    printf(" 2");
    registerPointer->next = (registerNode *)malloc(sizeof(registerNode));
    printf(" 3");
    // newNode->last = registerPointer;
    strcpy(registerPointer->next->word, newWord);
    registerPointer->next->last = registerPointer;
    printf(" 4");
    registerPointer = registerPointer->next;
    printf(" 5");
    // strcpy(registerPointer->word, newWord);
    printf(" 6");
    registerPointer->next = NULL;
  }
  printf("did this FINISH?!\n");
}

/* Method to print all nodes and node data in token linked list */
void printRegisterStack()
{
  registerNode *printer = registerHead;
  while (printer != NULL)
  {
    if (printer->next == NULL)
    {
      printf("%s\n", printer->word);
      printer = printer->next;
    }
    else
    {
      printf("%s, ", printer->word);
      printer = printer->next;
    }
  }
}

void printRegisterListBackwards()
{
  registerNode *printer = registerHead;
  while (printer != NULL)
  {
    if (printer->last == NULL)
    {
      printf("%s\n", printer->word);
      printer = printer->next;
    }
    else
    {
      printf("%s, ", printer->word);
      printer = printer->last;
    }
  }
}

/* Returns registerHead of token linked list */
registerNode *getRegisterHead()
{
  return registerHead;
}
